In [108]:
import pandas as pd


referendum_data = pd.read_csv(
    'data/EU-referendum-result-data.csv'
)

# ages = pd.read_csv(
#     'data/ages.csv'
# )
density = pd.read_csv(
    'data/density.csv'
)
# ethnic_groups = pd.read_csv(
#     'data/ethnic_groups.csv'
# )
health = pd.read_csv(
    'data/health.csv'
)
sex = pd.read_csv(
    'data/sex.csv'
)

areas_lat_lon = pd.read_csv(
    'data/areas_lat_lon.csv'
)


# health['Very good health'] = health['Very good health'].apply(lambda x: x.replace(",", ""))
# health['Good health'] = health['Good health'].apply(lambda x: x.replace(",", ""))
# health['Fair health'] = health['Fair health'].apply(lambda x: x.replace(",", ""))
# health['Very bad health'] = health['Very bad health'].apply(lambda x: x.replace(",", ""))
# health['Bad health'] = health['Bad health'].apply(lambda x: x.replace(",", ""))
# health['Area code']

# sex['Males'] = sex['Males'].apply(lambda x: x.replace(",", ""))
# sex['Females'] = sex['Females'].apply(lambda x: x.replace(",", ""))
# sex['Area code']


# density['Density']
# density['Area code']


health = health[
    ['Very good health',
    'Good health',
    'Fair health',
    'Very bad health',
    'Bad health',
    'Area code',]
]
sex = sex[['Males', 'Females', 'Area code']]
density = density[['Area code', 'Density']]
referendum_data = referendum_data[[
    'Area_Code', 'Area', 'Remain', 'Leave'
]]
referendum_data = referendum_data.rename(columns={'Area_Code': 'Area code'})
areas_lat_lon = areas_lat_lon[[
    'lad17cd', 'lat', 'long'
]]
areas_lat_lon=areas_lat_lon.rename(columns={'lad17cd': 'Area code'})


ward_to_district = pd.read_csv('data/ward_to_local_district.csv')
ward_to_district=ward_to_district.rename(columns={'WD18CD': 'ward_id', 'LAD18CD': 'Area code'})
ward_to_district=ward_to_district[['ward_id', 'Area code']]
# LAD18CD
# WD18CD

ward_codes = pd.read_csv('data/ward-codes-w-30-45.csv')
ward_codes=ward_codes.rename(columns={'ward': 'ward_id'})
ward_codes = ward_codes.merge(
    ward_to_district, on='ward_id', how='left'
)
# ward_codes=ward_codes[ward_codes['Area code'].notnull()]
# ward_codes.groupby("Area code").mean().sort_values("30-45w", ascending=False)
ward_codes['number'] = ward_codes['30-45w'] * ward_codes['pop'] 

ward_codes = ward_codes.drop_duplicates()
ward_result = ward_codes.groupby("Area code").sum().sort_values("number", ascending=False).reset_index()
ward_result = ward_result[['Area code', 'number']]
ward_result.head()
ward_codes.head()

ward_to_district_2 = pd.read_csv('data/ward_to_local_district.csv')
ward_to_district_2
ward_codes = pd.read_csv('data/ward-codes-w-30-45.csv')
ward_codes.sum()

# ward_codes = pd.read_csv('data/ward-codes-w-30-45.csv')
# ward_codes=ward_codes.rename(columns={'ward': 'ward_id'})
# ward_codes = ward_codes.merge(
#     ward_to_district, on='ward_id', how='left'
# )
referendum_data = referendum_data.merge(
    density, on='Area code', how='left'
)
referendum_data = referendum_data.merge(
    sex, on='Area code', how='left'
)

referendum_data = referendum_data.merge(
    health, on='Area code', how='left'
)

referendum_data = referendum_data.merge(
    areas_lat_lon, on='Area code', how='left'
)

def _clean(x):
    try:
        return int(x.replace(",", ""))
    except:
        return x

# referendum_data.to_csv("the_real_data.csv")
# referendum_data['Area code']
referendum_data[referendum_data['Area code'] == 'E07000220']
res = referendum_data.merge(ward_result, on="Area code", how="left")
res = res.sort_values("number", ascending=False)
res['remain_pct'] = res['Remain'] / (res['Remain'] + res['Leave'])
res['women_voters_pct'] = res['Females'].apply(_clean) / (res['Females'].apply(_clean) + res['Males'].apply(_clean))

# .apply(_clean)

res['very_good_health_pct'] = res['Very good health'] / (res['Very good health'] + res['Good health'] +res['Bad health'] + res['Fair health'] + res['Very bad health'])
res['very_bad_health_pct'] =  res['Very bad health'] / (res['Very good health'] + res['Good health'] + res['Bad health']+res['Fair health'] + res['Very bad health'])

res

,Area code,Area,Remain,Leave,Density,Males,Females,Very good health,Good health,Fair health,Very bad health,Bad health,lat,long,number,remain_pct,women_voters_pct
280,E06000052,Cornwall,140540,182665,1.5,"257,805","274,468","240,759","178,805","79,181","7,621","25,907",50.450230,-4.642490,49530.0,0.434832,0.515653
282,E06000054,Wiltshire,137258,151637,1.4,"231,754","239,227","234,318","160,362","57,221","4,106","14,974",51.328831,-1.926610,47863.0,0.475114,0.507933
125,E06000047,County Durham,113521,153877,2.3,"251,280","261,962","217,373","171,564","82,404","9,333","32,568",54.685131,-1.840500,40738.0,0.424539,0.510406
322,W06000015,Cardiff,101788,67816,24.7,"169,893","176,197","174,329","107,477","42,014","5,525","16,745",51.502541,-3.222120,36874.0,0.600151,0.509107
136,E06000049,Cheshire East,107962,113163,3.2,"181,409","188,718","181,595","123,065","47,306","3,914","14,247",53.167931,-2.292990,36016.0,0.488240,0.509874
211,E06000042,Milton Keynes,63393,67063,8.1,"123,116","125,705","124,826","86,778","26,929","2,333","7,955",52.072411,-0.740700,33680.0,0.485934,0.505203
5,E06000056,Central Bedfordshire,69670,89134,3.6,"126,044","128,337","125,019","90,360","29,202","2,128","7,672",51.999031,-0.477540,31257.0,0.438717,0.504507
362,E06000011,East Riding of Yorkshire,78779,120136,1.4,"163,388","170,791","151,003","116,859","48,307","4,133","13,877",53.881222,-0.662030,29451.0,0.396044,0.511076
126,E06000057,Northumberland,82022,96699,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,55.300369,-2.075210,28600.0,0.458939,NaN
377,E08000032,Bradford,104575,123913,14.3,"257,132","265,320","234,133","186,031","71,580","6,940","23,768",53.843819,-1.873890,28293.0,0.457683,0.507836
334,E06000051,Shropshire,78987,104166,1.0,"151,606","154,523","142,309","106,909","41,475","3,457","11,979",52.622120,-2.736670,27702.0,0.431262,0.504764
274,E06000025,South Gloucestershire,74928,83405,5.3,"130,424","132,343","129,141","91,675","30,940","2,455","8,556",51.546711,-2.469220,25345.0,0.473230,0.503652
279,E06000030,Swindon,51220,61745,9.1,"104,618","104,538","100,931","73,591","25,056","2,022","7,556",51.577629,-1.733670,25141.0,0.453415,0.499809
323,W06000016,Rhondda Cynon Taf,53973,62590,5.5,"114,635","119,775","105,154","69,544","37,208","5,108","17,396",51.621849,-3.413590,23874.0,0.463037,0.510964
318,W06000011,Swansea,58307,61936,6.3,"118,087","120,936","116,295","69,978","33,402","4,875","14,473",51.658058,-3.967230,22903.0,0.484910,0.505960
216,E07000004,Aylesbury Vale,52877,53956,1.9,"86,241","87,896","89,515","59,530","19,073","1,358","4,661",51.900379,-0.877460,21664.0,0.494950,0.504752
137,E06000050,Cheshire West and Chester,95455,98082,3.6,"160,586","169,022","159,777","108,967","42,604","4,001","14,259",53.163361,-2.702980,20925.0,0.493213,0.512797
273,E06000024,North Somerset,59572,64976,5.4,"98,463","104,103","93,803","70,435","27,670","2,382","8,276",51.397072,-2.754390,20583.0,0.478306,0.513921
374,E08000017,Doncaster,46922,104260,5.3,"149,230","153,172","131,738","102,983","45,748","4,951","16,982",53.526970,-1.108940,20349.0,0.310368,0.506518
210,E06000041,Wokingham,55272,42229,8.6,"76,464","77,916","83,759","51,808","14,566",937,"3,310",51.422958,-0.899350,18733.0,0.566886,0.504703
324,W06000018,Caerphilly,39178,53295,6.4,"87,701","91,105","79,382","54,272","28,488","3,820","12,844",51.650009,-3.197530,18617.0,0.423670,0.509519
332,E06000020,Telford and Wrekin,32954,56649,5.7,"82,549","84,092","76,439","57,198","22,609","2,372","8,023",52.714169,-2.489410,17807.0,0.367778,0.504630
331,E06000019,"Herefordshire, County of",44148,64122,0.8,"90,302","93,175","83,874","64,494","25,517","2,151","7,441",52.081539,-2.739310,16830.0,0.407758,0.507829
317,W06000010,Carmarthenshire,47654,55381,0.8,"89,837","93,940","82,638","55,618","30,011","4,035","11,475",51.894951,-4.211100,16698.0,0.462503,0.511163
206,E06000037,West Berkshire,48300,44977,2.2,"76,321","77,501","79,432","53,069","16,456","1,047","3,818",51.445591,-1.273640,16451.0,0.517813,0.503836
45,E07000242,East Hertfordshire,42372,42994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.864849,0.002739,16217.0,0.496357,NaN
269,E07000228,Mid Sussex,46471,41057,4.2,"68,462","71,398","72,448","47,524","14,938","1,086","3,864",51.059528,-0.102720,16019.0,0.530927,0.510496
375,E08000018,Rotherham,44115,93272,9.0,"126,247","131,033","111,232","87,237","39,278","4,419","15,114",53.395531,-1.286510,15918.0,0.321100,0.509301
133,E06000007,Warrington,52657,62487,11.2,"100,300","101,928","100,734","66,223","24,446","2,359","8,466",53.391628,-2.561670,15861.0,0.457314,0.504025
328,W06000022,Newport,32413,41236,7.6,"71,380","74,356","66,667","47,811","20,538","2,559","8,161",51.582321,-2.897690,15810.0,0.440101,0.510210
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
220,E07000061,Eastbourne,22845,30700,22.5,"47,559","51,853","42,818","35,193","15,251","1,438","4,712",50.774132,0.258699,NaN,0.426650,0.521597
221,E07000062,Hastings,20011,24339,30.4,"44,014","46,240","36,556","32,707","14,276","1,556","5,159",50.867680,0.579429,NaN,0.451206,0.512332
227,E07000086,Eastleigh,36172,39902,15.7,"61,384","63,815","61,561","44,190","14,538","1,093","3,817",50.948719,-1.329430,NaN,0.475484,0.509709
228,E07000087,Fareham,32210,39525,15.0,"54,634","56,947","54,170","39,284","13,638","1,000","3,489",50.853931,-1.237420,NaN,0.449014,0.510365
229,E07000088,Gosport,16671,29456,32.6,"40,736","41,886","37,447","29,915","11,224",821,"3,215",50.806412,-1.167250,NaN,0.361415,0.506959
231,E07000090,Havant,26582,44047,21.8,"58,607","62,077","53,474","43,275","17,188","1,575","5,172",50.872299,-1.004000,NaN,0.376361,0.514376
233,E07000092,Rushmoor,20384,28396,24.0,"46,757","47,050","46,970","33,340","10,099",773,"2,625",51.278149,-0.768070,NaN,0.417876,0.501562
254,E07000208,Epsom and Ewell,23596,21707,22.0,"36,412","38,690","39,208","25,355","7,988",535,"2,016",51.339451,-0.261720,NaN,0.520849,0.515166
258,E07000212,Runnymede,20259,24035,10.3,"39,148","41,362","41,319","27,451","8,767",602,"2,371",51.392731,-0.538550,NaN,0.457376,0.513750
259,E07000213,Spelthorne,22474,34135,21.3,"47,053","48,545","45,929","34,239","11,509",836,"3,085",51.415520,-0.462540,NaN,0.397004,0.507804
263,E07000217,Woking,31007,24214,15.6,"49,144","50,054","51,360","34,291","10,184",761,"2,602",51.308369,-0.579820,NaN,0.561507,0.504587
267,E07000226,Crawley,22388,31447,23.7,"52,698","53,899","50,751","38,279","12,856","1,032","3,679",51.123569,-0.195330,NaN,0.415863,0.505633
270,E07000229,Worthing,28851,32515,32.2,"50,384","54,256","46,272","37,777","15,082","1,154","4,355",50.833099,-0.401270,NaN,0.470146,0.518502
272,E06000023,"Bristol, City of",141027,87418,39.1,"213,071","215,163","209,024","143,283","52,446","5,425","18,056",51.471149,-2.577420,NaN,0.617335,0.502443
275,E06000026,Plymouth,53458,79997,32.1,"126,684","129,700","117,976","85,956","35,756","3,684","13,012",50.404942,-4.112990,NaN,0.400569,0.505882
278,E06000029,Poole,35741,49707,22.8,"72,121","75,524","68,689","51,486","19,849","1,780","5,841",50.740780,-1.953270,NaN,0.418278,0.511524
284,E07000041,Exeter,35270,28533,25.0,"57,211","60,562","58,775","39,301","14,075","1,291","4,331",50.717800,-3.513720,NaN,0.552795,0.514227
308,GI,Gibraltar,19322,823,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.959146,NaN
333,E06000021,Stoke-on-Trent,36027,81563,26.6,"123,995","125,013","104,510","86,311","38,179","4,652","15,356",53.017071,-2.158880,NaN,0.306378,0.502044
338,E07000195,Newcastle-under-Lyme,25477,43457,5.9,"61,206","62,665","55,311","42,716","17,802","1,730","6,312",53.003448,-2.326310,NaN,0.369585,0.505889
342,E07000199,Tamworth,13705,28424,24.9,"37,694","39,119","35,029","27,064","10,314","1,007","3,399",52.620312,-1.684510,NaN,0.325310,0.509276
344,E07000219,Nuneaton and Bedworth,23736,46095,15.9,"61,441","63,811","55,086","44,255","18,133","1,759","6,019",52.500938,-1.479650,NaN,0.339906,0.509461
354,E08000025,Birmingham,223451,227251,40.1,"527,806","545,239","488,568","363,904","148,782","17,686","54,105",52.484039,-1.881410,NaN,0.495784,0.508123
356,E08000027,Dudley,56780,118446,31.9,"153,819","159,106","132,825","111,905","47,828","4,449","15,918",52.495129,-2.101710,NaN,0.324039,0.508448
357,E08000028,Sandwell,49004,98250,36.0,"151,592","156,471","129,182","107,081","48,087","5,542","18,171",52.514771,-2.007710,NaN,0.332786,0.507919
359,E08000030,Walsall,43572,92007,25.9,"132,319","137,004","113,525","94,650","41,653","4,527","14,968",52.605030,-1.970440,NaN,0.321377,0.508698
360,E08000031,Wolverhampton,44138,73798,35.9,"123,441","126,029","104,263","88,168","39,096","4,147","13,796",52.597881,-2.127460,NaN,0.374254,0.505187
361,E06000010,"Kingston upon Hull, City of",36709,76646,35.9,"128,420","127,986","110,555","89,572","38,102","4,130","14,047",53.769791,-0.303800,NaN,0.323841,0.499154
368,E07000165,Harrogate,48211,46374,1.2,"77,037","80,832","79,934","53,313","18,633","1,291","4,698",54.077080,-1.581610,NaN,0.509711,0.512019
380,E08000035,Leeds,194863,192474,13.6,"367,935","383,550","361,295","254,023","95,515","9,148","31,504",53.822731,-1.507360,NaN,0.503084,0.510389

,Area code,Area,Remain,Leave,Density_x,Males_x,Females_x,Very good health_x,Good health_x,Fair health_x,...,Very good health_y,Good health_y,Fair health_y,Very bad health_y,Bad health_y,lat_y,long_y,number,number2,remain_pct
280,E06000052,Cornwall,140540,182665,1.5,"257,805","274,468","240,759","178,805","79,181",...,"240,759","178,805","79,181","7,621","25,907",50.450230,-4.642490,49530.0,561349.0,0.434832
282,E06000054,Wiltshire,137258,151637,1.4,"231,754","239,227","234,318","160,362","57,221",...,"234,318","160,362","57,221","4,106","14,974",51.328831,-1.926610,47863.0,496043.0,0.475114
125,E06000047,County Durham,113521,153877,2.3,"251,280","261,962","217,373","171,564","82,404",...,"217,373","171,564","82,404","9,333","32,568",54.685131,-1.840500,40738.0,444768.0,0.424539
322,W06000015,Cardiff,101788,67816,24.7,"169,893","176,197","174,329","107,477","42,014",...,"174,329","107,477","42,014","5,525","16,745",51.502541,-3.222120,36874.0,362756.0,0.600151
136,E06000049,Cheshire East,107962,113163,3.2,"181,409","188,718","181,595","123,065","47,306",...,"181,595","123,065","47,306","3,914","14,247",53.167931,-2.292990,36016.0,378846.0,0.488240
211,E06000042,Milton Keynes,63393,67063,8.1,"123,116","125,705","124,826","86,778","26,929",...,"124,826","86,778","26,929","2,333","7,955",52.072411,-0.740700,33680.0,267521.0,0.485934
5,E06000056,Central Bedfordshire,69670,89134,3.6,"126,044","128,337","125,019","90,360","29,202",...,"125,019","90,360","29,202","2,128","7,672",51.999031,-0.477540,31257.0,280030.0,0.438717
362,E06000011,East Riding of Yorkshire,78779,120136,1.4,"163,388","170,791","151,003","116,859","48,307",...,"151,003","116,859","48,307","4,133","13,877",53.881222,-0.662030,29451.0,338061.0,0.396044
126,E06000057,Northumberland,82022,96699,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,55.300369,-2.075210,28600.0,319030.0,0.458939
377,E08000032,Bradford,104575,123913,14.3,"257,132","265,320","234,133","186,031","71,580",...,"234,133","186,031","71,580","6,940","23,768",53.843819,-1.873890,28293.0,275855.0,0.457683
334,E06000051,Shropshire,78987,104166,1.0,"151,606","154,523","142,309","106,909","41,475",...,"142,309","106,909","41,475","3,457","11,979",52.622120,-2.736670,27702.0,317459.0,0.431262
274,E06000025,South Gloucestershire,74928,83405,5.3,"130,424","132,343","129,141","91,675","30,940",...,"129,141","91,675","30,940","2,455","8,556",51.546711,-2.469220,25345.0,247436.0,0.473230
279,E06000030,Swindon,51220,61745,9.1,"104,618","104,538","100,931","73,591","25,056",...,"100,931","73,591","25,056","2,022","7,556",51.577629,-1.733670,25141.0,220363.0,0.453415
323,W06000016,Rhondda Cynon Taf,53973,62590,5.5,"114,635","119,775","105,154","69,544","37,208",...,"105,154","69,544","37,208","5,108","17,396",51.621849,-3.413590,23874.0,239127.0,0.463037
318,W06000011,Swansea,58307,61936,6.3,"118,087","120,936","116,295","69,978","33,402",...,"116,295","69,978","33,402","4,875","14,473",51.658058,-3.967230,22903.0,245480.0,0.484910
216,E07000004,Aylesbury Vale,52877,53956,1.9,"86,241","87,896","89,515","59,530","19,073",...,"89,515","59,530","19,073","1,358","4,661",51.900379,-0.877460,21664.0,196020.0,0.494950
137,E06000050,Cheshire West and Chester,95455,98082,3.6,"160,586","169,022","159,777","108,967","42,604",...,"159,777","108,967","42,604","4,001","14,259",53.163361,-2.702980,20925.0,222481.0,0.493213
273,E06000024,North Somerset,59572,64976,5.4,"98,463","104,103","93,803","70,435","27,670",...,"93,803","70,435","27,670","2,382","8,276",51.397072,-2.754390,20583.0,212834.0,0.478306
374,E08000017,Doncaster,46922,104260,5.3,"149,230","153,172","131,738","102,983","45,748",...,"131,738","102,983","45,748","4,951","16,982",53.526970,-1.108940,20349.0,213397.0,0.310368
210,E06000041,Wokingham,55272,42229,8.6,"76,464","77,916","83,759","51,808","14,566",...,"83,759","51,808","14,566",937,"3,310",51.422958,-0.899350,18733.0,164980.0,0.566886
324,W06000018,Caerphilly,39178,53295,6.4,"87,701","91,105","79,382","54,272","28,488",...,"79,382","54,272","28,488","3,820","12,844",51.650009,-3.197530,18617.0,180795.0,0.423670
332,E06000020,Telford and Wrekin,32954,56649,5.7,"82,549","84,092","76,439","57,198","22,609",...,"76,439","57,198","22,609","2,372","8,023",52.714169,-2.489410,17807.0,175768.0,0.367778
331,E06000019,"Herefordshire, County of",44148,64122,0.8,"90,302","93,175","83,874","64,494","25,517",...,"83,874","64,494","25,517","2,151","7,441",52.081539,-2.739310,16830.0,191041.0,0.407758
317,W06000010,Carmarthenshire,47654,55381,0.8,"89,837","93,940","82,638","55,618","30,011",...,"82,638","55,618","30,011","4,035","11,475",51.894951,-4.211100,16698.0,186452.0,0.462503
206,E06000037,West Berkshire,48300,44977,2.2,"76,321","77,501","79,432","53,069","16,456",...,"79,432","53,069","16,456","1,047","3,818",51.445591,-1.273640,16451.0,158473.0,0.517813
45,E07000242,East Hertfordshire,42372,42994,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,51.864849,0.002739,16217.0,147080.0,0.496357
269,E07000228,Mid Sussex,46471,41057,4.2,"68,462","71,398","72,448","47,524","14,938",...,"72,448","47,524","14,938","1,086","3,864",51.059528,-0.102720,16019.0,148345.0,0.530927
375,E08000018,Rotherham,44115,93272,9.0,"126,247","131,033","111,232","87,237","39,278",...,"111,232","87,237","39,278","4,419","15,114",53.395531,-1.286510,15918.0,159834.0,0.321100
133,E06000007,Warrington,52657,62487,11.2,"100,300","101,928","100,734","66,223","24,446",...,"100,734","66,223","24,446","2,359","8,466",53.391628,-2.561670,15861.0,158431.0,0.457314
328,W06000022,Newport,32413,41236,7.6,"71,380","74,356","66,667","47,811","20,538",...,"66,667","47,811","20,538","2,559","8,161",51.582321,-2.897690,15810.0,151485.0,0.440101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
220,E07000061,Eastbourne,22845,30700,22.5,"47,559","51,853","42,818","35,193","15,251",...,"42,818","35,193","15,251","1,438","4,712",50.774132,0.258699,NaN,NaN,0.426650
221,E07000062,Hastings,20011,24339,30.4,"44,014","46,240","36,556","32,707","14,276",...,"36,556","32,707","14,276","1,556","5,159",50.867680,0.579429,NaN,NaN,0.451206
227,E07000086,Eastleigh,36172,39902,15.7,"61,384","63,815","61,561","44,190","14,538",...,"61,561","44,190","14,538","1,093","3,817",50.948719,-1.329430,NaN,NaN,0.475484
228,E07000087,Fareham,32210,39525,15.0,"54,634","56,947","54,170","39,284","13,638",...,"54,170","39,284","13,638","1,000","3,489",50.853931,-1.237420,NaN,NaN,0.449014
229,E07000088,Gosport,16671,29456,32.6,"40,736","41,886","37,447","29,915","11,224",...,"37,447","29,915","11,224",821,"3,215",50.806412,-1.167250,NaN,NaN,0.361415
231,E07000090,Havant,26582,44047,21.8,"58,607","62,077","53,474","43,275","17,188",...,"53,474","43,275","17,188","1,575","5,172",50.872299,-1.004000,NaN,NaN,0.376361
233,E07000092,Rushmoor,20384,28396,24.0,"46,757","47,050","46,970","33,340","10,099",...,"46,970","33,340","10,099",773,"2,625",51.278149,-0.768070,NaN,NaN,0.417876
254,E07000208,Epsom and Ewell,23596,21707,22.0,"36,412","38,690","39,208","25,355","7,988",...,"39,208","25,355","7,988",535,"2,016",51.339451,-0.261720,NaN,NaN,0.520849
258,E07000212,Runnymede,20259,24035,10.3,"39,148","41,362","41,319","27,451","8,767",...,"41,319","27,451","8,767",602,"2,371",51.392731,-0.538550,NaN,NaN,0.457376
259,E07000213,Spelthorne,22474,34135,21.3,"47,053","48,545","45,929","34,239","11,509",...,"45,929","34,239","11,509",836,"3,085",51.415520,-0.462540,NaN,NaN,0.397004
263,E07000217,Woking,31007,24214,15.6,"49,144","50,054","51,360","34,291","10,184",...,"51,360","34,291","10,184",761,"2,602",51.308369,-0.579820,NaN,NaN,0.561507
267,E07000226,Crawley,22388,31447,23.7,"52,698","53,899","50,751","38,279","12,856",...,"50,751","38,279","12,856","1,032","3,679",51.123569,-0.195330,NaN,NaN,0.415863
270,E07000229,Worthing,28851,32515,32.2,"50,384","54,256","46,272","37,777","15,082",...,"46,272","37,777","15,082","1,154","4,355",50.833099,-0.401270,NaN,NaN,0.470146
272,E06000023,"Bristol, City of",141027,87418,39.1,"213,071","215,163","209,024","143,283","52,446",...,"209,024","143,283","52,446","5,425","18,056",51.471149,-2.577420,NaN,NaN,0.617335
275,E06000026,Plymouth,53458,79997,32.1,"126,684","129,700","117,976","85,956","35,756",...,"117,976","85,956","35,756","3,684","13,012",50.404942,-4.112990,NaN,NaN,0.400569
278,E06000029,Poole,35741,49707,22.8,"72,121","75,524","68,689","51,486","19,849",...,"68,689","51,486","19,849","1,780","5,841",50.740780,-1.953270,NaN,NaN,0.418278
284,E07000041,Exeter,35270,28533,25.0,"57,211","60,562","58,775","39,301","14,075",...,"58,775","39,301","14,075","1,291","4,331",50.717800,-3.513720,NaN,NaN,0.552795
308,GI,Gibraltar,19322,823,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.959146
333,E06000021,Stoke-on-Trent,36027,81563,26.6,"123,995","125,013","104,510","86,311","38,179",...,"104,510","86,311","38,179","4,652","15,356",53.017071,-2.158880,NaN,NaN,0.306378
338,E07000195,Newcastle-under-Lyme,25477,43457,5.9,"61,206","62,665","55,311","42,716","17,802",...,"55,311","42,716","17,802","1,730","6,312",53.003448,-2.326310,NaN,NaN,0.369585
342,E07000199,Tamworth,13705,28424,24.9,"37,694","39,119","35,029","27,064","10,314",...,"35,029","27,064","10,314","1,007","3,399",52.620312,-1.684510,NaN,NaN,0.325310
344,E07000219,Nuneaton and Bedworth,23736,46095,15.9,"61,441","63,811","55,086","44,255","18,133",...,"55,086","44,255","18,133","1,759","6,019",52.500938,-1.479650,NaN,NaN,0.339906
354,E08000025,Birmingham,223451,227251,40.1,"527,806","545,239","488,568","363,904","148,782",...,"488,568","363,904","148,782","17,686","54,105",52.484039,-1.881410,NaN,NaN,0.495784
356,E08000027,Dudley,56780,118446,31.9,"153,819","159,106","132,825","111,905","47,828",...,"132,825","111,905","47,828","4,449","15,918",52.495129,-2.101710,NaN,NaN,0.324039
357,E08000028,Sandwell,49004,98250,36.0,"151,592","156,471","129,182","107,081","48,087",...,"129,182","107,081","48,087","5,542","18,171",52.514771,-2.007710,NaN,NaN,0.332786
359,E08000030,Walsall,43572,92007,25.9,"132,319","137,004","113,525","94,650","41,653",...,"113,525","94,650","41,653","4,527","14,968",52.605030,-1.970440,NaN,NaN,0.321377
360,E08000031,Wolverhampton,44138,73798,35.9,"123,441","126,029","104,263","88,168","39,096",...,"104,263","88,168","39,096","4,147","13,796",52.597881,-2.127460,NaN,NaN,0.374254
361,E06000010,"Kingston upon Hull, City of",36709,76646,35.9,"128,420","127,986","110,555","89,572","38,102",...,"110,555","89,572","38,102","4,130","14,047",53.769791,-0.303800,NaN,NaN,0.323841
368,E07000165,Harrogate,48211,46374,1.2,"77,037","80,832","79,934","53,313","18,633",...,"79,934","53,313","18,633","1,291","4,698",54.077080,-1.581610,NaN,NaN,0.509711
380,E08000035,Leeds,194863,192474,13.6,"367,935","383,550","361,295","254,023","95,515",...,"361,295","254,023","95,515","9,148","31,504",53.822731,-1.507360,NaN,NaN,0.503084